-- copy data into raw tables with copy command
COPY INTO MOVIE_DB.STAGE.DIM_AWARDS_RAW
FROM (SELECT S.$1, S.$2, S.$3, CURRENT_TIMESTAMP() FROM @MOVIE_DB.EXTERNAL_STAGES.AWS_STAGE S)
PATTERN = '.*awards.*.csv'
FILE_FORMAT = (FORMAT_NAME = 'MOVIE_DB.FILE_FORMATS.CSV_FILE_FORMAT', ERROR_ON_COLUMN_COUNT_MISMATCH = FALSE);  


COPY INTO MOVIE_DB.STAGE.DIM_MOVIE_DETAILS_RAW
FROM (SELECT S.$1, S.$2, S.$3, S.$4, S.$5, S.$6, S.$7, CURRENT_TIMESTAMP() FROM @MOVIE_DB.EXTERNAL_STAGES.AWS_STAGE S)
PATTERN = '.*movie.*.csv'
FILE_FORMAT = (FORMAT_NAME = 'MOVIE_DB.FILE_FORMATS.CSV_FILE_FORMAT', ERROR_ON_COLUMN_COUNT_MISMATCH = FALSE)
ON_ERROR = 'CONTINUE';

COPY INTO MOVIE_DB.STAGE.DIM_RATING_RAW
FROM (SELECT S.$1, S.$2, S.$3, CURRENT_TIMESTAMP() FROM @MOVIE_DB.EXTERNAL_STAGES.AWS_STAGE S)
PATTERN = '.*rating.*.csv'
FILE_FORMAT = (FORMAT_NAME = 'MOVIE_DB.FILE_FORMATS.CSV_FILE_FORMAT', ERROR_ON_COLUMN_COUNT_MISMATCH = FALSE);

COPY INTO MOVIE_DB.STAGE.DIM_ACTOR_RAW
FROM (SELECT S.$1, S.$2, S.$3, S.$4, CURRENT_TIMESTAMP() FROM @MOVIE_DB.EXTERNAL_STAGES.AWS_STAGE S)
PATTERN = '.*actor.*.csv'
FILE_FORMAT = (FORMAT_NAME = 'MOVIE_DB.FILE_FORMATS.CSV_FILE_FORMAT', ERROR_ON_COLUMN_COUNT_MISMATCH = FALSE);

COPY INTO MOVIE_DB.STAGE.DIM_WRITER_RAW
FROM (SELECT S.$1, S.$2, S.$3, S.$4, CURRENT_TIMESTAMP() FROM @MOVIE_DB.EXTERNAL_STAGES.AWS_STAGE S)
PATTERN = '.*writer.*.csv'
FILE_FORMAT = (FORMAT_NAME = 'MOVIE_DB.FILE_FORMATS.CSV_FILE_FORMAT', ERROR_ON_COLUMN_COUNT_MISMATCH = FALSE);

COPY INTO MOVIE_DB.STAGE.DIM_DIRECTOR_RAW
FROM (SELECT S.$1, S.$2, S.$3, S.$4, CURRENT_TIMESTAMP() FROM @MOVIE_DB.EXTERNAL_STAGES.AWS_STAGE S)
PATTERN = '.*director.*.csv'
FILE_FORMAT = (FORMAT_NAME = 'MOVIE_DB.FILE_FORMATS.CSV_FILE_FORMAT', ERROR_ON_COLUMN_COUNT_MISMATCH = FALSE);

COPY INTO MOVIE_DB.STAGE.FACT_MOVIE_RAW
FROM (SELECT S.$1, S.$2, S.$3, S.$4, S.$5, S.$6, CURRENT_TIMESTAMP() FROM @MOVIE_DB.EXTERNAL_STAGES.AWS_STAGE S)
PATTERN = '.*fact.*.csv'
FILE_FORMAT = (FORMAT_NAME = 'MOVIE_DB.FILE_FORMATS.CSV_FILE_FORMAT', ERROR_ON_COLUMN_COUNT_MISMATCH = FALSE);
